#!/bin/bash

# 1. Everything starting with 'a'
find . -type f -name "a*"

# 2. Everything ending with 'z'
find . -type f -name "*z"

# 3. Everything starting with 'z' and ending with 'a!'
find . -type f -name "z*a!"
